# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/hprc-jetson/.local/bin/cmake

# The command to remove a file.
RM = /home/hprc-jetson/.local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hprc-jetson/vishal/GitHub/od_pipelines

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hprc-jetson/vishal/GitHub/od_pipelines

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/hprc-jetson/.local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/hprc-jetson/.local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hprc-jetson/vishal/GitHub/od_pipelines/CMakeFiles /home/hprc-jetson/vishal/GitHub/od_pipelines//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hprc-jetson/vishal/GitHub/od_pipelines/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pipelines.out

# Build rule for target.
pipelines.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pipelines.out
.PHONY : pipelines.out

# fast build rule for target.
pipelines.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/build
.PHONY : pipelines.out/fast

#=============================================================================
# Target rules for targets named lsf_stream

# Build rule for target.
lsf_stream: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lsf_stream
.PHONY : lsf_stream

# fast build rule for target.
lsf_stream/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/build
.PHONY : lsf_stream/fast

src/ScheduleEngine.o: src/ScheduleEngine.cu.o
.PHONY : src/ScheduleEngine.o

# target to build an object file
src/ScheduleEngine.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/ScheduleEngine.cu.o
.PHONY : src/ScheduleEngine.cu.o

src/ScheduleEngine.i: src/ScheduleEngine.cu.i
.PHONY : src/ScheduleEngine.i

# target to preprocess a source file
src/ScheduleEngine.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/ScheduleEngine.cu.i
.PHONY : src/ScheduleEngine.cu.i

src/ScheduleEngine.s: src/ScheduleEngine.cu.s
.PHONY : src/ScheduleEngine.s

# target to generate assembly for a file
src/ScheduleEngine.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/ScheduleEngine.cu.s
.PHONY : src/ScheduleEngine.cu.s

src/cnmem.o: src/cnmem.cpp.o
.PHONY : src/cnmem.o

# target to build an object file
src/cnmem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/cnmem.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/cnmem.cpp.o
.PHONY : src/cnmem.cpp.o

src/cnmem.i: src/cnmem.cpp.i
.PHONY : src/cnmem.i

# target to preprocess a source file
src/cnmem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/cnmem.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/cnmem.cpp.i
.PHONY : src/cnmem.cpp.i

src/cnmem.s: src/cnmem.cpp.s
.PHONY : src/cnmem.s

# target to generate assembly for a file
src/cnmem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/cnmem.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/cnmem.cpp.s
.PHONY : src/cnmem.cpp.s

src/coarsened_forward_convolution.o: src/coarsened_forward_convolution.cu.o
.PHONY : src/coarsened_forward_convolution.o

# target to build an object file
src/coarsened_forward_convolution.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/coarsened_forward_convolution.cu.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/coarsened_forward_convolution.cu.o
.PHONY : src/coarsened_forward_convolution.cu.o

src/coarsened_forward_convolution.i: src/coarsened_forward_convolution.cu.i
.PHONY : src/coarsened_forward_convolution.i

# target to preprocess a source file
src/coarsened_forward_convolution.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/coarsened_forward_convolution.cu.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/coarsened_forward_convolution.cu.i
.PHONY : src/coarsened_forward_convolution.cu.i

src/coarsened_forward_convolution.s: src/coarsened_forward_convolution.cu.s
.PHONY : src/coarsened_forward_convolution.s

# target to generate assembly for a file
src/coarsened_forward_convolution.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/coarsened_forward_convolution.cu.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/coarsened_forward_convolution.cu.s
.PHONY : src/coarsened_forward_convolution.cu.s

src/dag.o: src/dag.cu.o
.PHONY : src/dag.o

# target to build an object file
src/dag.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/dag.cu.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/dag.cu.o
.PHONY : src/dag.cu.o

src/dag.i: src/dag.cu.i
.PHONY : src/dag.i

# target to preprocess a source file
src/dag.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/dag.cu.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/dag.cu.i
.PHONY : src/dag.cu.i

src/dag.s: src/dag.cu.s
.PHONY : src/dag.s

# target to generate assembly for a file
src/dag.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/dag.cu.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/dag.cu.s
.PHONY : src/dag.cu.s

src/image.o: src/image.cpp.o
.PHONY : src/image.o

# target to build an object file
src/image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/image.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/image.cpp.o
.PHONY : src/image.cpp.o

src/image.i: src/image.cpp.i
.PHONY : src/image.i

# target to preprocess a source file
src/image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/image.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/image.cpp.i
.PHONY : src/image.cpp.i

src/image.s: src/image.cpp.s
.PHONY : src/image.s

# target to generate assembly for a file
src/image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/image.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/image.cpp.s
.PHONY : src/image.cpp.s

src/layer_params.o: src/layer_params.cu.o
.PHONY : src/layer_params.o

# target to build an object file
src/layer_params.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/layer_params.cu.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/layer_params.cu.o
.PHONY : src/layer_params.cu.o

src/layer_params.i: src/layer_params.cu.i
.PHONY : src/layer_params.i

# target to preprocess a source file
src/layer_params.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/layer_params.cu.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/layer_params.cu.i
.PHONY : src/layer_params.cu.i

src/layer_params.s: src/layer_params.cu.s
.PHONY : src/layer_params.s

# target to generate assembly for a file
src/layer_params.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/layer_params.cu.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/layer_params.cu.s
.PHONY : src/layer_params.cu.s

src/lsf_scheduler.o: src/lsf_scheduler.cu.o
.PHONY : src/lsf_scheduler.o

# target to build an object file
src/lsf_scheduler.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/lsf_scheduler.cu.o
.PHONY : src/lsf_scheduler.cu.o

src/lsf_scheduler.i: src/lsf_scheduler.cu.i
.PHONY : src/lsf_scheduler.i

# target to preprocess a source file
src/lsf_scheduler.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/lsf_scheduler.cu.i
.PHONY : src/lsf_scheduler.cu.i

src/lsf_scheduler.s: src/lsf_scheduler.cu.s
.PHONY : src/lsf_scheduler.s

# target to generate assembly for a file
src/lsf_scheduler.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/lsf_scheduler.cu.s
.PHONY : src/lsf_scheduler.cu.s

src/lsf_stream.o: src/lsf_stream.cu.o
.PHONY : src/lsf_stream.o

# target to build an object file
src/lsf_stream.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/lsf_stream.cu.o
.PHONY : src/lsf_stream.cu.o

src/lsf_stream.i: src/lsf_stream.cu.i
.PHONY : src/lsf_stream.i

# target to preprocess a source file
src/lsf_stream.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/lsf_stream.cu.i
.PHONY : src/lsf_stream.cu.i

src/lsf_stream.s: src/lsf_stream.cu.s
.PHONY : src/lsf_stream.s

# target to generate assembly for a file
src/lsf_stream.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/lsf_stream.cu.s
.PHONY : src/lsf_stream.cu.s

src/neural_net.o: src/neural_net.cu.o
.PHONY : src/neural_net.o

# target to build an object file
src/neural_net.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/neural_net.cu.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/neural_net.cu.o
.PHONY : src/neural_net.cu.o

src/neural_net.i: src/neural_net.cu.i
.PHONY : src/neural_net.i

# target to preprocess a source file
src/neural_net.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/neural_net.cu.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/neural_net.cu.i
.PHONY : src/neural_net.cu.i

src/neural_net.s: src/neural_net.cu.s
.PHONY : src/neural_net.s

# target to generate assembly for a file
src/neural_net.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/neural_net.cu.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/neural_net.cu.s
.PHONY : src/neural_net.cu.s

src/pipelines.o: src/pipelines.cu.o
.PHONY : src/pipelines.o

# target to build an object file
src/pipelines.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/pipelines.cu.o
.PHONY : src/pipelines.cu.o

src/pipelines.i: src/pipelines.cu.i
.PHONY : src/pipelines.i

# target to preprocess a source file
src/pipelines.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/pipelines.cu.i
.PHONY : src/pipelines.cu.i

src/pipelines.s: src/pipelines.cu.s
.PHONY : src/pipelines.s

# target to generate assembly for a file
src/pipelines.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/pipelines.cu.s
.PHONY : src/pipelines.cu.s

src/user_iface.o: src/user_iface.cu.o
.PHONY : src/user_iface.o

# target to build an object file
src/user_iface.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/user_iface.cu.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/user_iface.cu.o
.PHONY : src/user_iface.cu.o

src/user_iface.i: src/user_iface.cu.i
.PHONY : src/user_iface.i

# target to preprocess a source file
src/user_iface.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/user_iface.cu.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/user_iface.cu.i
.PHONY : src/user_iface.cu.i

src/user_iface.s: src/user_iface.cu.s
.PHONY : src/user_iface.s

# target to generate assembly for a file
src/user_iface.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/user_iface.cu.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/user_iface.cu.s
.PHONY : src/user_iface.cu.s

src/utilities.o: src/utilities.cu.o
.PHONY : src/utilities.o

# target to build an object file
src/utilities.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/utilities.cu.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/utilities.cu.o
.PHONY : src/utilities.cu.o

src/utilities.i: src/utilities.cu.i
.PHONY : src/utilities.i

# target to preprocess a source file
src/utilities.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/utilities.cu.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/utilities.cu.i
.PHONY : src/utilities.cu.i

src/utilities.s: src/utilities.cu.s
.PHONY : src/utilities.s

# target to generate assembly for a file
src/utilities.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/utilities.cu.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/utilities.cu.s
.PHONY : src/utilities.cu.s

src/utils.o: src/utils.cu.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/utils.cu.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/utils.cu.o
.PHONY : src/utils.cu.o

src/utils.i: src/utils.cu.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/utils.cu.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/utils.cu.i
.PHONY : src/utils.cu.i

src/utils.s: src/utils.cu.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pipelines.out.dir/build.make CMakeFiles/pipelines.out.dir/src/utils.cu.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lsf_stream.dir/build.make CMakeFiles/lsf_stream.dir/src/utils.cu.s
.PHONY : src/utils.cu.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lsf_stream"
	@echo "... pipelines.out"
	@echo "... src/ScheduleEngine.o"
	@echo "... src/ScheduleEngine.i"
	@echo "... src/ScheduleEngine.s"
	@echo "... src/cnmem.o"
	@echo "... src/cnmem.i"
	@echo "... src/cnmem.s"
	@echo "... src/coarsened_forward_convolution.o"
	@echo "... src/coarsened_forward_convolution.i"
	@echo "... src/coarsened_forward_convolution.s"
	@echo "... src/dag.o"
	@echo "... src/dag.i"
	@echo "... src/dag.s"
	@echo "... src/image.o"
	@echo "... src/image.i"
	@echo "... src/image.s"
	@echo "... src/layer_params.o"
	@echo "... src/layer_params.i"
	@echo "... src/layer_params.s"
	@echo "... src/lsf_scheduler.o"
	@echo "... src/lsf_scheduler.i"
	@echo "... src/lsf_scheduler.s"
	@echo "... src/lsf_stream.o"
	@echo "... src/lsf_stream.i"
	@echo "... src/lsf_stream.s"
	@echo "... src/neural_net.o"
	@echo "... src/neural_net.i"
	@echo "... src/neural_net.s"
	@echo "... src/pipelines.o"
	@echo "... src/pipelines.i"
	@echo "... src/pipelines.s"
	@echo "... src/user_iface.o"
	@echo "... src/user_iface.i"
	@echo "... src/user_iface.s"
	@echo "... src/utilities.o"
	@echo "... src/utilities.i"
	@echo "... src/utilities.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

